# Site settings
title: 마마플레이트 Mama Plate
email: platemama@gmail.com
description: 신선하고 편리한 음식을 주제로 건강한 식문화를 선도합니다. 천연발효종을 사용하여 소화 잘 되는 빵 일체의 화학 보존제를 첨가하지 않고 유기농 설탕을 사용한 건강한 빵을 만듭니다.


baseurl: momslab.github.io
url: momslab.net
twitter_username:
github_username:

# Build settings
markdown: kramdown
